apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kgraa13xm-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:1089f58c44d1fc51d6a24f422e9636d42fb4a1d2@sha256:5403afc9a06751b0d9ca29e79437c3f9f96f598350170ae45dccd061cc724688
          name: container-image
